packages:
  - 'apps/*'
  - 'libs/*'

shamefullyHoist: true

allowBuilds:
  '@scarf/scarf': false
  grpc-tools: true
  lefthook: true
  protobufjs: true
  unrs-resolver: true

overrides:
  glob: ^13.0.6
  test-exclude: ^8.0.0
