export const SERVICE_TOKENS = {
  USERS_SERVICE: 'USERS_SERVICE',
  ORDERS_SERVICE: 'ORDERS_SERVICE',
  PAYMENTS_SERVICE: 'PAYMENTS_SERVICE',
  PRODUCTS_SERVICE: 'PRODUCTS_SERVICE',
} as const;

export type ServiceToken = (typeof SERVICE_TOKENS)[keyof typeof SERVICE_TOKENS];
