export enum OrderStatus {
  PENDING = 'PENDING',
  AWAITING_STOCK = 'AWAITING_STOCK',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAID = 'PAID',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
  REFUNDING = 'REFUNDING',
  REFUNDED = 'REFUNDED',
}
